version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kyoho
    container_name: kyoho_dev
    volumes:
      - ${PWD}:${PWD}
    restart: always
    working_dir: ${PWD}
    command: ["/bin/bash", "./entrypoint.dev.sh"]
